### ISSUE TITLE
Errors trying to run this on macOS (Sierra)

### ISSUE THREAD

**Issue by jwhitmire** [chuckdee68/IEDLCDEditor#4]
Once I got all of the dependencies installed ok, the only error I saw was to do with the code in the msgBox method.  The `ctypes.windll.user32.MessageBoxW` call is windows specific.  I haven't had time to mess with it, but I'm guessing there is an easy way to detect the environment and use either tkMessageBox or EasyDialogs instead.  Here is the full error output:

```
Traceback (most recent call last):
  File "IEDLCDE.py", line 432, in <module>
    gfx = Graphics()
  File "IEDLCDE.py", line 106, in __init__
    msret = msgBox("No COM ports found!\nCheck that your Infinity Ergodox is plugged in\nDo you want to retry?", "No keyboard found", 5)
  File "IEDLCDE.py", line 423, in msgBox
    result = ctypes.windll.user32.MessageBoxW(0, text, caption, utype)
AttributeError: module 'ctypes' has no attribute 'windll'
```

**Comment by d3v-null** [comment]
Same issue with macOS Sierra as well

```
2016-10-16 16:07:13.811 Python[72427:1425445] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/w5/20kpfg8x32x379d5r3j0vl5c0000gn/T/org.python.python.savedState
Traceback (most recent call last):
  File "Source/IEDLCDE.py", line 432, in <module>
    gfx = Graphics()
  File "Source/IEDLCDE.py", line 67, in __init__
    msgBox("Error loading image 'F{0}.bmp'\nThe app will now close".format(n), "File not found", 0)
  File "Source/IEDLCDE.py", line 423, in msgBox
    result = ctypes.windll.user32.MessageBoxW(0, text, caption, utype)
AttributeError: 'module' object has no attribute 'windll'
```

**Comment by LuuuuX** [comment]
I'll keep this in mind, but I also invite you or anyone else to try and fix the issue and then push it.

**Comment by hymnis** [comment]
I have been tinkering with the code a bit to have it run on Linux. My changes should also make is usable on macOS, with the correct libraries installed. If anyone is still interested they could try using the code from commit [e39c87bfd4e97bd2f15a9abac0f6a699f0b2df6f](https://github.com/hymnis/IEDLCDEditor/commit/e39c87bfd4e97bd2f15a9abac0f6a699f0b2df6f) in my fork.

There are quite a number of revisions but most are fixes to keep the code PEP8 compliant and weeding out lint errors and warnings. It runs well on my Linux system (Ubuntu 16.10) and I have been using both preview and written and flashed files with success.

Any feedback or input would be appreciated and I'll answer questions that might arise as soon as possible.

@LuuuuX - Great job in getting this project started. It's a great tool for applying colors and images for the layers. I hope you don't take any offence to my edits.

**Comment by twhiston** [comment]
I'm also started working on an osx port of this today, which is available [here](https://github.com/twhiston/IEDLCDEditor/tree/feature/osx-compatibility). Currently it boots into the gui and on the surface level works, but it's got a few serious issues that need addressing before it could be called usable. 

- The binary does not build properly. When it tries to write to the file it throws an error of 'ascii codec cant decode byte 0xff in postition 0: ordinal not in range', however when i remove the call to `.encode('latin-1')` (line 388) it writes correctly (and the binary is loadable) but this seems to mess up the detection of byte sequences and the colour and function data is never written, causing the image write to fail (and of course skipping all that data). Unfortunately I don't know enough about python in general to have a deeper insight here and would appreciate any pointers.
- all the windll stuff is removed and I tried to find a quick and easy cross platform replacement to do the dialog boxes rather than hack in something just for OSX. Easygui is old but seemed to work with little effort which should mean we dont need to  write any platform specific code there. It also slightly simplifies the calls to deal with windows, and allows us to return a value, so it is possible to do away with some of the global constants for return values.
- colors of the image 'frames' do not update currently, from screenshots it seems like they should.
- the code for getting the serial ports doesn't work on osx and i replaced it with something that hopefully works cross platform, but it needs testing by people on windows/linux/etc....
- Tested with Python 2.7.14 

It would be super awesome if someone using linux or windows could test out the branch i made and see if it works properly etc.... and help we weed out the issues that are platform specific. It's so super cool that this tools exists, and i'd love to help get it working for everyone :)
